CREATE SCHEMA IF NOT EXISTS db_appointment;

CREATE TABLE db_appointment.tb_calendar (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   date_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   is_booked BOOLEAN NOT NULL,
   CONSTRAINT pk_tb_calendar PRIMARY KEY (id)
);

CREATE TABLE db_appointment.tb_appointment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   doctor_id BIGINT NOT NULL,
   patient_id BIGINT NOT NULL,
   calendar_id BIGINT,
   status VARCHAR(255) NOT NULL,
   CONSTRAINT pk_tb_appointment PRIMARY KEY (id)
);

ALTER TABLE db_appointment.tb_appointment ADD CONSTRAINT FK_TB_APPOINTMENT_ON_CALENDAR FOREIGN KEY (calendar_id) REFERENCES db_appointment.tb_calendar (id);