CREATE TABLE db_user.tb_doctor (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   email VARCHAR(255),
   birthday date,
   crm VARCHAR(255),
   address BYTEA,
   status VARCHAR(255),
   CONSTRAINT pk_tb_doctor PRIMARY KEY (id)
);